name: Test workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: echo "test"
      shell: bash

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: test bye
        run: echo "Bye"
        shell: bash